### ISSUE TITLE
Installation error message when Scanning folders for symlinks

### ISSUE THREAD

**Issue by robd** [PSPDFKit/react-native#6]
First of all - thanks for providing this integration and v clear installation instructions which I was able to get up and running on ios despite being new to PSPDFKit and React Native.

The only slight issue I saw was the following error at the end of the `react-native install github:PSPDFKit/react-native` step. I'm not sure if it's a problem. I guess it may well be a react native or yarn issue, but I thought I should mention it.

    success Saved 1 new dependency.
    └─ react-native-pspdfkit@1.1.0
    ✨  Done in 4.89s.
    Scanning 559 folders for symlinks in /path/to/app/node_modules (5ms)
    { Error: Cannot find module '/path/to/app/node_modules/github:PSPDFKit/react-native/package.json'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at getRNPMConfig (/path/to/app/node_modules/react-native/local-cli/core/default.config.js:32:3)
        at Object.getDependencyConfig (/path/to/app/node_modules/react-native/local-cli/core/default.config.js:78:18)
        at deps.reduce (/path/to/app/node_modules/react-native/local-cli/link/getDependencyConfig.js:9:24)
        at Array.reduce (native)
        at getDependencyConfig (/path/to/app/node_modules/react-native/local-cli/link/getDependencyConfig.js:6:15)
        at Object.link (/path/to/app/node_modules/react-native/local-cli/link/link.js:150:24) code: 'MODULE_NOT_FOUND' }

**Comment by juliangrosshauser** [comment]
Thank you for reporting this and for your kind words!

This looks like a `react-native` issue. Also happens when you use `npm` instead of `yarn`.

We now switched to

```
yarn add github:PSPDFKit/react-native
react-native link react-native-pspdfkit
```

instead of

```
react-native install github:PSPDFKit/react-native
```

because this streamlines our Android integration process and doesn't show any error messages.

**Comment by robd** [comment]
That's great - thanks for sorting this out.
